# Generated by Django 2.2.4 on 2019-09-18 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Giorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_giorno', models.CharField(choices=[('Lunedì', 'Lunedì'), ('Martedì', 'Martedì'), ('Mercoledì', 'Mercoledì'), ('Giovedì', 'Giovedì'), ('Venerdì', 'Venerdì'), ('Sabato', 'Sabato')], default='Lunedì', max_length=15)),
                ('ora_corso', models.TimeField(default='00:00')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.IntegerField(choices=[(1, 'sala 1'), (2, 'sala 2'), (3, 'sala 3'), (4, 'sala 4'), (5, 'sala 5')], default='sala 1')),
                ('capienza', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_corso', models.CharField(default='VUOTO', max_length=30)),
                ('immagine_corso', models.ImageField(default='missing.jpg', upload_to='')),
                ('num_utenti_prenotati', models.PositiveIntegerField(default=1)),
                ('giorno', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='corso.Giorno')),
                ('lista_attesa', models.ManyToManyField(blank=True, related_name='lista_attesa', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='corso.Sala')),
                ('utenti_prenotati', models.ManyToManyField(related_name='utenti_prenotati', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
